services:
  streamer:
    build: .
    container_name: streamer-nginx
    ports:
      - "8000:80"
    volumes:
      - ../packager/.playlists:/var/www/playlists:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
